production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch('PUMA_THREADS', 5).to_i + 1 %>
development:
  adapter: postgresql
  encoding: unicode
  database: halo_stats_dev
  username: postgres
  password:
